import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";
import { CartProvider } from "@/components/cart-context";
import { WishlistProvider } from "@/components/wishlist-context";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ClerkProvider } from "@clerk/nextjs";
import Script from "next/script"; // Import Script for chatbot

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "E-Commerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head className="md:p-8 lg:p-11">
          {/* Chatbot Configuration Script */}
          <Script
            id="chatbot-config"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `
                window.embeddedChatbotConfig = {
                  chatbotId: "uhmozxi9UYSh5lFd_QXTB", // Your Chatbot ID
                  domain: "www.chatbase.co"
                };
              `,
            }}
          />
          <Script
            src="https://www.chatbase.co/embed.min.js"
            data-chatbot-id="uhmozxi9UYSh5lFd_QXTB" // Your Chatbot ID
            data-domain="www.chatbase.co"
            strategy="afterInteractive"
            defer
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <WishlistProvider>
            <CartProvider>
              <NavBar />
              {children}
              <Footer />
              <ToastContainer position="bottom-right" autoClose={3000} />
            </CartProvider>
          </WishlistProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
